<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bookings · Admin</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900">
<div class="min-h-screen lg:grid lg:grid-cols-[260px_1fr]">
<aside class="bg-slate-950 p-6 text-white"><p class="text-xs font-bold uppercase tracking-[.25em] text-amber-400">Offroad Booking</p><h1 class="mt-2 text-xl font-black">Admin Panel</h1><nav class="mt-8 space-y-2 text-sm"><a href="{{ route('admin.dashboard') }}" class="block rounded-xl px-4 py-3 text-slate-300">Dashboard</a><a href="{{ route('admin.bookings.index') }}" class="block rounded-xl bg-amber-500 px-4 py-3 font-bold text-slate-950">Bookings</a><a href="{{ route('admin.payments.index') }}" class="block rounded-xl px-4 py-3 text-slate-300">Payments</a></nav></aside>
<main class="p-5 sm:p-8 lg:p-10">
<header><p class="text-sm font-semibold text-amber-600">Operations</p><h2 class="mt-1 text-3xl font-black">Bookings</h2><p class="mt-2 text-slate-500">Kelola status booking dan assignment driver.</p></header>
<form method="GET" class="mt-6 grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-4">
<input name="search" value="{{ request('search') }}" placeholder="Booking/customer" class="rounded-lg border-slate-300">
<select name="status" class="rounded-lg border-slate-300"><option value="">Semua status</option>@foreach(\App\Enums\BookingStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->value }}</option>@endforeach</select>
<select name="payment_status" class="rounded-lg border-slate-300"><option value="">Semua pembayaran</option>@foreach(\App\Enums\PaymentStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('payment_status')===$status->value)>{{ $status->value }}</option>@endforeach</select>
<button class="rounded-lg bg-slate-950 px-5 py-2.5 font-bold text-white">Filter</button>
</form>
<div class="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Booking</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Nilai</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y">@forelse($bookings as $booking)<tr><td class="px-5 py-4"><p class="font-bold">{{ $booking->booking_code }}</p><p class="text-xs text-slate-500">{{ $booking->tourPackage?->name }}</p></td><td class="px-5 py-4">{{ $booking->customer?->name }}</td><td class="px-5 py-4">{{ $booking->tour_date->format('d M Y') }}</td><td class="px-5 py-4 font-semibold">Rp{{ number_format($booking->total_amount,0,',','.') }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs">{{ $booking->status->value }} / {{ $booking->payment_status->value }}</span></td><td class="px-5 py-4"><a class="font-bold text-amber-700" href="{{ route('admin.bookings.show',$booking) }}">Buka</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">Belum ada booking.</td></tr>@endforelse</tbody></table></div><div class="border-t p-4">{{ $bookings->links() }}</div></div>
</main></div></body></html>
