<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Withdrawals · Admin</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900"><main class="mx-auto max-w-7xl p-5 sm:p-8">
<a href="{{ route('admin.dashboard') }}" class="text-sm font-bold text-amber-700">← Dashboard</a>
<header class="mt-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-amber-600">Finance operations</p><h1 class="text-3xl font-black">Withdrawal Queue</h1><p class="mt-2 text-slate-500">Approve, reject, dan tandai pembayaran poin driver.</p></div></header>
<form method="GET" class="mt-6 grid gap-3 rounded-2xl border bg-white p-4 shadow-sm sm:grid-cols-[180px_1fr_auto]"><select name="status" class="rounded-lg border-slate-300"><option value="">Semua status</option>@foreach(\App\Enums\WithdrawalStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ $status->value }}</option>@endforeach</select><input name="search" value="{{ request('search') }}" placeholder="Cari nama atau email driver" class="rounded-lg border-slate-300"><button class="rounded-lg bg-slate-950 px-5 py-2 font-bold text-white">Filter</button></form>
<div class="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Driver</th><th class="px-5 py-3">Poin</th><th class="px-5 py-3">Jumlah</th><th class="px-5 py-3">Rekening</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y">
@forelse($withdrawals as $item)<tr><td class="px-5 py-4"><p class="font-bold">{{ $item->driverProfile?->user?->name }}</p><p class="text-xs text-slate-500">{{ $item->driverProfile?->user?->email }}</p></td><td class="px-5 py-4">{{ number_format($item->points) }}</td><td class="px-5 py-4 font-semibold">Rp{{ number_format($item->amount,0,',','.') }}</td><td class="px-5 py-4">{{ $item->bank_name }} · {{ $item->account_number }}</td><td class="px-5 py-4">{{ $item->status->value }}</td><td class="px-5 py-4"><a href="{{ route('admin.withdrawals.show',$item) }}" class="font-bold text-amber-700">Tinjau</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">Belum ada withdrawal.</td></tr>@endforelse
</tbody></table></div><div class="border-t p-4">{{ $withdrawals->links() }}</div></div>
</main></body></html>