<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{{ $driverProfile->user?->name }} · Driver Verification</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900"><main class="mx-auto max-w-6xl p-5 sm:p-8">
<a href="{{ route('admin.drivers.index') }}" class="text-sm font-bold text-amber-700">← Kembali ke driver</a>
@if(session('success'))<div class="mt-4 rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mt-4 rounded-xl bg-red-50 p-4 text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<header class="mt-5 flex flex-col gap-4 rounded-2xl bg-slate-950 p-6 text-white sm:flex-row sm:items-end sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[.2em] text-amber-400">Driver detail</p><h1 class="mt-2 text-3xl font-black">{{ $driverProfile->user?->name }}</h1><p class="mt-2 text-slate-400">{{ $driverProfile->user?->email }} · {{ $driverProfile->user?->phone }}</p></div><div><p class="text-sm text-slate-400">Verification</p><p class="text-2xl font-black">{{ $driverProfile->verification_status->value }}</p></div></header>
<section class="mt-6 grid gap-6 lg:grid-cols-[1fr_360px]"><div class="space-y-6">
<article class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Profil driver</h2><dl class="mt-4 grid gap-4 sm:grid-cols-2"><div><dt class="text-xs uppercase text-slate-500">Nomor SIM</dt><dd class="font-semibold">{{ $driverProfile->license_number }}</dd></div><div><dt class="text-xs uppercase text-slate-500">Nomor identitas</dt><dd class="font-semibold">{{ $driverProfile->identity_number }}</dd></div><div><dt class="text-xs uppercase text-slate-500">Tanggal lahir</dt><dd class="font-semibold">{{ optional($driverProfile->date_of_birth)->format('d M Y') }}</dd></div><div><dt class="text-xs uppercase text-slate-500">Status operasional</dt><dd class="font-semibold">{{ $driverProfile->status->value }}</dd></div><div class="sm:col-span-2"><dt class="text-xs uppercase text-slate-500">Alamat</dt><dd class="font-semibold">{{ $driverProfile->address }}</dd></div></dl></article>
<article class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Dokumen driver</h2><div class="mt-4 space-y-3">@forelse($driverProfile->documents as $document)<div class="flex items-center justify-between rounded-xl border p-4"><div><p class="font-bold">{{ $document->type?->value ?? $document->type }}</p><p class="text-xs text-slate-500">{{ $document->verification_status?->value ?? $document->verification_status }}</p></div><a href="{{ asset('storage/'.$document->file_path) }}" target="_blank" class="font-bold text-amber-700">Buka</a></div>@empty<p class="text-sm text-slate-500">Belum ada dokumen.</p>@endforelse</div></article>
<article class="rounded-2xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Kendaraan</h2><div class="mt-4 space-y-4">@forelse($driverProfile->vehicles as $vehicle)<div class="rounded-xl border p-4"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold">{{ $vehicle->name }} · {{ $vehicle->plate_number }}</p><p class="text-sm text-slate-500">{{ $vehicle->brand }} {{ $vehicle->model }} · kapasitas {{ $vehicle->capacity }} · {{ $vehicle->verification_status->value }}</p></div></div><form method="POST" action="{{ route('admin.drivers.vehicles.update',[$driverProfile,$vehicle]) }}" class="mt-4 grid gap-3 sm:grid-cols-[160px_1fr_auto]">@csrf @method('PATCH')<select name="verification_status" class="rounded-lg border-slate-300"><option value="approved">approved</option><option value="rejected">rejected</option></select><input name="rejection_reason" placeholder="Alasan wajib jika rejected" class="rounded-lg border-slate-300"><button class="rounded-lg bg-slate-950 px-4 py-2 font-bold text-white">Simpan</button></form></div>@empty<p class="text-sm text-slate-500">Belum ada kendaraan.</p>@endforelse</div></article>
</div><aside><article class="rounded-2xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Keputusan driver</h2><form method="POST" action="{{ route('admin.drivers.update',$driverProfile) }}" class="mt-4 space-y-3">@csrf @method('PATCH')<select name="verification_status" class="w-full rounded-lg border-slate-300"><option value="approved">approved</option><option value="rejected">rejected</option></select><textarea name="rejection_reason" rows="4" placeholder="Alasan wajib jika rejected" class="w-full rounded-lg border-slate-300"></textarea><button class="w-full rounded-lg bg-amber-500 px-4 py-2.5 font-bold text-slate-950">Simpan keputusan</button></form>@if($driverProfile->rejection_reason)<div class="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-800">{{ $driverProfile->rejection_reason }}</div>@endif</article></aside></section>
</main></body></html>
