<!DOCTYPE html>
<html lang="id">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Pembayaran · Admin Offroad Booking</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900">
<div class="min-h-screen lg:grid lg:grid-cols-[260px_1fr]">
<aside class="bg-slate-950 px-6 py-5 text-white lg:min-h-screen"><p class="text-xs font-semibold uppercase tracking-[.25em] text-amber-400">Offroad Booking</p><h1 class="mt-2 text-xl font-black">Admin Panel</h1><nav class="mt-8 grid grid-cols-2 gap-2 text-sm lg:grid-cols-1"><a href="{{ route('admin.dashboard') }}" class="rounded-xl px-4 py-3 text-slate-300 hover:bg-white/10">Dashboard</a><span class="rounded-xl px-4 py-3 text-slate-500">Bookings</span><a href="{{ route('admin.payments.index') }}" class="rounded-xl bg-amber-500 px-4 py-3 font-bold text-slate-950">Payments</a><span class="rounded-xl px-4 py-3 text-slate-500">Drivers</span><span class="rounded-xl px-4 py-3 text-slate-500">Vehicles</span><span class="rounded-xl px-4 py-3 text-slate-500">Withdrawals</span></nav><form method="POST" action="{{ route('admin.logout') }}" class="mt-10 border-t border-white/10 pt-6">@csrf<button class="text-sm text-slate-400 hover:text-white">Keluar</button></form></aside>
<main class="p-5 sm:p-8 lg:p-10">
<header><p class="text-sm font-semibold text-amber-600">Finance operations</p><h2 class="mt-1 text-3xl font-black">Verifikasi pembayaran</h2><p class="mt-2 text-slate-500">Tinjau bukti pembayaran dan perbarui status transaksi customer.</p></header>
<section class="mt-7 grid gap-3 sm:grid-cols-3">@foreach(['pending'=>'Pending','paid'=>'Paid','failed'=>'Failed'] as $key=>$label)<a href="{{ route('admin.payments.index',['status'=>$key]) }}" class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-sm text-slate-500">{{ $label }}</p><p class="mt-2 text-3xl font-black">{{ number_format($counts[$key] ?? 0) }}</p></a>@endforeach</section>
<form method="GET" class="mt-6 grid gap-3 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:grid-cols-[1fr_180px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Booking, nama, atau email" class="rounded-xl border-slate-300"><select name="status" class="rounded-xl border-slate-300"><option value="">Semua status</option>@foreach(['unpaid','pending','paid','refunded','failed'] as $status)<option value="{{ $status }}" @selected(request('status')===$status)>{{ ucfirst($status) }}</option>@endforeach</select><button class="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white">Filter</button></form>
<div class="mt-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr><th class="px-5 py-3">Booking</th><th class="px-5 py-3">Customer</th><th class="px-5 py-3">Jumlah</th><th class="px-5 py-3">Metode</th><th class="px-5 py-3">Status</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($payments as $payment)<tr><td class="px-5 py-4"><p class="font-bold">{{ $payment->booking->booking_code }}</p><p class="text-xs text-slate-500">{{ $payment->booking->tourPackage?->name }}</p></td><td class="px-5 py-4"><p>{{ $payment->customer->name }}</p><p class="text-xs text-slate-500">{{ $payment->customer->email }}</p></td><td class="px-5 py-4 font-semibold">Rp{{ number_format($payment->amount,0,',','.') }}</td><td class="px-5 py-4">{{ $payment->method }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-bold">{{ $payment->status->value }}</span></td><td class="px-5 py-4 text-right"><a class="font-bold text-amber-700" href="{{ route('admin.payments.show',$payment) }}">Tinjau</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-slate-500">Tidak ada pembayaran.</td></tr>@endforelse</tbody></table></div><div class="border-t border-slate-100 px-5 py-4">{{ $payments->links() }}</div></div>
</main></div></body></html>
