<!DOCTYPE html>
<html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Travel Groups · Admin</title>@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-slate-100 text-slate-900"><main class="mx-auto max-w-7xl p-5 sm:p-8">
<div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><a href="{{ route('admin.dashboard') }}" class="text-sm font-bold text-amber-700">← Dashboard</a><p class="mt-4 text-xs font-bold uppercase tracking-[.2em] text-amber-600">Operations</p><h1 class="mt-2 text-3xl font-black">Travel Groups</h1><p class="mt-2 text-slate-600">Kelola rombongan, anggota, dan booking terkait.</p></div><a href="{{ route('admin.travel-groups.create') }}" class="rounded-xl bg-slate-950 px-5 py-3 text-sm font-bold text-white">Buat group</a></div>
@if(session('success'))<div class="mt-5 rounded-xl bg-emerald-50 p-4 text-emerald-800">{{ session('success') }}</div>@endif
@if($errors->any())<div class="mt-5 rounded-xl bg-red-50 p-4 text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="GET" class="mt-6 grid gap-3 rounded-2xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_180px_180px_auto]"><input name="search" value="{{ request('search') }}" placeholder="Nama group" class="rounded-xl border-slate-300"><select name="status" class="rounded-xl border-slate-300"><option value="">Semua status</option>@foreach(\App\Enums\TravelGroupStatus::cases() as $status)<option value="{{ $status->value }}" @selected(request('status')===$status->value)>{{ ucfirst($status->value) }}</option>@endforeach</select><select name="source" class="rounded-xl border-slate-300"><option value="">Semua sumber</option>@foreach(\App\Enums\TravelGroupSource::cases() as $source)<option value="{{ $source->value }}" @selected(request('source')===$source->value)>{{ ucfirst($source->value) }}</option>@endforeach</select><button class="rounded-xl bg-amber-500 px-5 py-3 font-bold">Filter</button></form>
<div class="mt-6 overflow-hidden rounded-2xl border bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-slate-200 text-sm"><thead class="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th class="px-5 py-4">Group</th><th class="px-5 py-4">Leader</th><th class="px-5 py-4">Anggota</th><th class="px-5 py-4">Booking</th><th class="px-5 py-4">Status</th><th class="px-5 py-4"></th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($travelGroups as $group)<tr><td class="px-5 py-4"><p class="font-bold">{{ $group->name }}</p><p class="text-xs text-slate-500">{{ $group->source->value }} · limit {{ $group->member_limit ?: '∞' }}</p></td><td class="px-5 py-4">{{ $group->leader?->name ?: 'Belum ada' }}</td><td class="px-5 py-4">{{ $group->members_count }}</td><td class="px-5 py-4">{{ $group->bookings_count }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold">{{ $group->status->value }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('admin.travel-groups.show',$group) }}" class="font-bold text-amber-700">Detail</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-10 text-center text-slate-500">Belum ada travel group.</td></tr>@endforelse</tbody></table></div><div class="border-t px-5 py-4">{{ $travelGroups->links() }}</div></div>
</main></body></html>
